import { createUc2Module } from "@/modules/uc2-report";
import { InMemoryReportRepository } from "@/modules/uc2-report/adapters/InMemoryReportRepository";
import { InMemoryAuditRepository } from "@/modules/uc2-report/adapters/InMemoryAuditRepository";
import { DecisionQueryService } from "@/modules/uc2-report/services/DecisionQueryService";
import { Clock, IdGenerator } from "@/shared/contracts/Clock";
import type {
  AlertReader,
  AttemptReader,
  DistributionReader,
  OccupancyEventReader,
  ReportDecisionReader,
} from "@/shared/contracts/types";
import { createUc4Module } from "@/modules/uc4-analysis";
import type { AuditLogger } from "@/modules/uc4-analysis/adapters/AuditLogger";
import { MockPartnerChannel } from "@/modules/uc4-analysis/adapters/MockPartnerChannel";
import type { OrganizationReader } from "@/modules/uc4-analysis/adapters/PartnerChannel";
import { PrismaShareLogRepository } from "@/modules/uc4-analysis/adapters/prisma/PrismaShareLogRepository";
import { PrismaSnapshotRepository } from "@/modules/uc4-analysis/adapters/prisma/PrismaSnapshotRepository";
import { PrismaSupplyStockReader } from "@/modules/uc4-analysis/adapters/prisma/PrismaSupplyStockReader";
import { PrismaAlertReader } from "@/modules/uc4-analysis/adapters/prisma/PrismaAlertReader";
import { PrismaAttemptReader } from "@/modules/uc4-analysis/adapters/prisma/PrismaAttemptReader";
import { PrismaOccupancyEventReader } from "@/modules/uc4-analysis/adapters/prisma/PrismaOccupancyEventReader";
import { PrismaDistributionReader } from "@/modules/uc4-analysis/adapters/prisma/PrismaDistributionReader";
import { PrismaOrganizationReader } from "@/modules/uc4-analysis/adapters/prisma/PrismaOrganizationReader";
import { InMemoryShareLogRepository } from "@/shared/infra/InMemoryShareLogRepository";
import { InMemorySnapshotRepository } from "@/shared/infra/InMemorySnapshotRepository";
import { InMemorySupplyStockReader } from "@/shared/infra/InMemorySupplyStockReader";
import { InMemoryAlertReader } from "@/shared/infra/InMemoryAlertReader";
import { InMemoryAttemptReader } from "@/shared/infra/InMemoryAttemptReader";
import { InMemoryOccupancyEventReader } from "@/shared/infra/InMemoryOccupancyEventReader";
import { InMemoryDistributionReader } from "@/shared/infra/InMemoryDistributionReader";
import { InMemoryOrganizationReader } from "@/shared/infra/InMemoryOrganizationReader";

// 1. Production implementations for infrastructure
const prodClock: Clock = {
  now: () => new Date(),
};

const prodIdGenerator: IdGenerator = {
  // Uses Node's built-in crypto module to generate standard UUIDs
  next: () => crypto.randomUUID(),
};

import { PrismaReportRepository } from "@/modules/uc2-report/adapters/PrismaReportRepository";
import { PrismaAuditRepository } from "@/modules/uc2-report/adapters/PrismaAuditRepository";

// 2. Initialize Repositories conditionally based on environment variable
const isPrisma = process.env.DATA_STORE === "prisma";

export const reports = isPrisma ? new PrismaReportRepository() : new InMemoryReportRepository();
export const audits = isPrisma ? new PrismaAuditRepository() : new InMemoryAuditRepository();

// 3. Wire the UC2 Module
// This `uc2` object is exported and used by all API routes.
export const uc2 = createUc2Module({
  reports,
  audits,
  clock: prodClock,
  ids: prodIdGenerator,
});

// 4. Real clock / id generator for UC4 (per README: SystemClock + UuidGenerator)
class SystemClock implements Clock {
  now(): Date {
    return new Date();
  }
}

class UuidGenerator implements IdGenerator {
  next(): string {
    return crypto.randomUUID();
  }
}

// 5. UC4 repositories — chosen by DATA_STORE ('memory' | 'prisma')
const uc4SnapshotRepository = isPrisma
  ? new PrismaSnapshotRepository()
  : new InMemorySnapshotRepository();
const uc4ShareLogRepository = isPrisma
  ? new PrismaShareLogRepository()
  : new InMemoryShareLogRepository();

// UC1 / UC3 readers: real Prisma implementations or in-memory fakes.
const alertReader = isPrisma
  ? new PrismaAlertReader()
  : new InMemoryAlertReader();
const attemptReader = isPrisma
  ? new PrismaAttemptReader()
  : new InMemoryAttemptReader();
const occupancyReader = isPrisma
  ? new PrismaOccupancyEventReader()
  : new InMemoryOccupancyEventReader();
const distributionReader = isPrisma
  ? new PrismaDistributionReader()
  : new InMemoryDistributionReader();
const supplyStockReader = isPrisma
  ? new PrismaSupplyStockReader()
  : new InMemorySupplyStockReader();
const decisionReader = new DecisionQueryService(audits);

// Partner-side organization reader.
const organizationReader = isPrisma
  ? new PrismaOrganizationReader()
  : new InMemoryOrganizationReader();
const partnerChannel = new MockPartnerChannel({ next: () => Math.random() }, 0.2);

// Audit sink: structured console lines until a persistent audit store exists.
const auditLogger: AuditLogger = {
  logGeneration: (reportId, actorId) =>
    console.log(`[audit] report ${reportId} generated by ${actorId}`),
  logFailure: (reason, actorId) =>
    console.log(`[audit] generation failed (${reason}) by ${actorId}`),
  logShare: (reportId, outcomes, actorId) =>
    console.log(
      `[audit] report ${reportId} shared with ${outcomes.length} recipient(s) by ${actorId}`,
    ),
};

// 6. Wire the UC4 Module
// This `uc4` object is exported and used by all UC4 API routes.
export const uc4 = createUc4Module({
  snapshotRepository: uc4SnapshotRepository,
  shareLogRepository: uc4ShareLogRepository,
  alertReader,
  attemptReader,
  decisionReader,
  occupancyReader,
  distributionReader,
  supplyStockReader,
  organizationReader,
  partnerChannel,
  auditLogger,
  clock: new SystemClock(),
  idGenerator: new UuidGenerator(),
});
