import type { District } from '../domain';
import { seedId } from './ids';

export const D = {
  COLOMBO: seedId(1, 1),
  GAMPAHA: seedId(1, 2),
  KEGALLE: seedId(1, 3),
  KANDY: seedId(1, 4),
  GALLE: seedId(1, 5),
  RATNAPURA: seedId(1, 6),
  KALUTARA: seedId(1, 7),
  MATALE: seedId(1, 8),
  NUWARA_ELIYA: seedId(1, 9),
  MATARA: seedId(1, 10),
  HAMBANTOTA: seedId(1, 11),
  JAFFNA: seedId(1, 12),
  KILINOCHCHI: seedId(1, 13),
  MANNAR: seedId(1, 14),
  VAVUNIYA: seedId(1, 15),
  MULLAITIVU: seedId(1, 16),
  BATTICALOA: seedId(1, 17),
  AMPARA: seedId(1, 18),
  TRINCOMALEE: seedId(1, 19),
  KURUNEGALA: seedId(1, 20),
  PUTTALAM: seedId(1, 21),
  ANURADHAPURA: seedId(1, 22),
  POLONNARUWA: seedId(1, 23),
  BADULLA: seedId(1, 24),
  MONARAGALA: seedId(1, 25),
} as const;

export const DISTRICTS: District[] = [
  { id: D.COLOMBO, name: 'Colombo' },
  { id: D.GAMPAHA, name: 'Gampaha' },
  { id: D.KEGALLE, name: 'Kegalle' },
  { id: D.KANDY, name: 'Kandy' },
  { id: D.GALLE, name: 'Galle' },
  { id: D.RATNAPURA, name: 'Ratnapura' },
  { id: D.KALUTARA, name: 'Kalutara' },
  { id: D.MATALE, name: 'Matale' },
  { id: D.NUWARA_ELIYA, name: 'Nuwara Eliya' },
  { id: D.MATARA, name: 'Matara' },
  { id: D.HAMBANTOTA, name: 'Hambantota' },
  { id: D.JAFFNA, name: 'Jaffna' },
  { id: D.KILINOCHCHI, name: 'Kilinochchi' },
  { id: D.MANNAR, name: 'Mannar' },
  { id: D.VAVUNIYA, name: 'Vavuniya' },
  { id: D.MULLAITIVU, name: 'Mullaitivu' },
  { id: D.BATTICALOA, name: 'Batticaloa' },
  { id: D.AMPARA, name: 'Ampara' },
  { id: D.TRINCOMALEE, name: 'Trincomalee' },
  { id: D.KURUNEGALA, name: 'Kurunegala' },
  { id: D.PUTTALAM, name: 'Puttalam' },
  { id: D.ANURADHAPURA, name: 'Anuradhapura' },
  { id: D.POLONNARUWA, name: 'Polonnaruwa' },
  { id: D.BADULLA, name: 'Badulla' },
  { id: D.MONARAGALA, name: 'Monaragala' },
];