import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Link from 'next/link';
import { Suspense } from 'react';
import { RoleSwitcherLoader } from '@/components/RoleSwitcherLoader';

const NAV = [
  { href: '/warnings', label: 'Warnings' },
  { href: '/report', label: 'Report' },
  { href: '/officer/reports', label: 'Review' },
  { href: '/resources', label: 'Resources' },
  { href: '/analysis', label: 'Analysis' },
];

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col bg-slate-50 text-slate-900">
        <header className="flex items-center justify-between border-b bg-white px-6 py-3 shadow-sm">
          <nav className="flex items-center gap-6 text-sm font-medium">
            <Link href="/" className="text-lg font-bold tracking-tight text-blue-700">
              DEWECS
            </Link>
            {NAV.map((n) => (
              <Link
                key={n.href}
                href={n.href}
                className="text-slate-600 transition hover:text-blue-600"
              >
                {n.label}
              </Link>
            ))}
          </nav>
          <Suspense fallback={<div className="h-8 w-32 animate-pulse bg-slate-200 rounded" />}>
            <RoleSwitcherLoader />
          </Suspense>
        </header>
        <main className="flex-1 p-6">{children}</main>
      </body>
    </html>
  );
}
